FROM node:20-alpine as build
WORKDIR /app
COPY package.json .
RUN npm install --force
COPY . .
RUN npm run build

# RUN ls -al /app/dist

FROM nginx:1.21-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 9080
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]