upstream api {
    server api:8000;
}

upstream client{
    server client;
}

server{
    listen 80;

    # Increase client body size to 50MB
    client_max_body_size 50M;



    location / {
        proxy_pass http://client;
        proxy_buffer_size 16k;
        proxy_buffers 8 16k;
        proxy_busy_buffers_size 32k;
    }

    location /api {
        rewrite /api/(.*) /$1 break;
        proxy_pass http://api;
        # Add proxy buffer settings
        proxy_buffer_size 16k;
        proxy_buffers 8 16k;
        proxy_busy_buffers_size 32k;
    }

}