upstream api {
    server api:8000;
}

upstream client{
    server client;
}

server {
    listen 80 default_server;
    server_name app.courierhq.io/;
    return 301 https://app.courierhq.io/$request_uri;
}

server{
    listen 80;

     client_max_body_size 50M;

    location / {
        proxy_pass http://client;
        # Add proxy buffer settings
        proxy_buffer_size 16k;
        proxy_buffers 8 16k;
        proxy_busy_buffers_size 32k;
    }


    location /api {
        rewrite /api/(.*) /$1 break;
        proxy_pass http://api;
        # Add proxy buffer settings
        proxy_buffer_size 16k;
        proxy_buffers 8 16k;
        proxy_busy_buffers_size 32k;
    }

    location /admin {
        rewrite /api/admin/(.*) /$1 break;
        proxy_pass http://api;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }



    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/app.courierhq.io//fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/app.courierhq.io//privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # proxy_send_timeout 180s;
    proxy_read_timeout 180s;
}